# Site settings
email: jk@devicezero.de
baseurl: ""
paginate: 3
paginate_path: "/blog/page-:num"
google_analytics: "UA-11722448-1"

# SEO settings
title: hello world, this is jonas
description: a part of the internet where jonas is writing down his thoughts
url: "http://blog.devicezero.de"
twitter_username: jonaskroeger
default_img:

# Profile settings
name: Jonas Kröger
profile_img: /assets/media/profile.jpg
profile: Jonas is a freelance product manager and web developer. He translates between developers and humans. Born in Germany he now travels the world and works remotely. His goal is to collect memories and meet new people instead of owning things.
social:
  instagram: https://www.instagram.com/devicezero/
  twitter: https://twitter.com/jonaskroeger


# Build settings
include: []
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", _"drafts", "vendor", "docker-compose.yml"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
